/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.laboratorio1;

import javax.swing.ButtonGroup;

/**
 *
 * @author dgualotuna
 */
public class Pedido extends javax.swing.JFrame {
    ButtonGroup rdbtnGroup = new ButtonGroup();
    /**
     * Creates new form VentanaPedido
     */
    public Pedido() {
        initComponents();
        rdbtnGroup.add(rdbtnFirst);
        rdbtnGroup.add(rdbtnSecond);
        rdbtnGroup.add(rdbtnThird);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblErrorName = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        cmbxType = new javax.swing.JComboBox<>();
        lblErrorType = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        lblErrorSize = new javax.swing.JLabel();
        lblDistributor = new javax.swing.JLabel();
        rdbtnFirst = new javax.swing.JRadioButton();
        rdbtnSecond = new javax.swing.JRadioButton();
        rdbtnThird = new javax.swing.JRadioButton();
        lblErrorDistributor = new javax.swing.JLabel();
        lblDeliverAddress = new javax.swing.JLabel();
        lblErrorDeliverAddress = new javax.swing.JLabel();
        chckbxPrincipal = new javax.swing.JCheckBox();
        chckbxSecondary = new javax.swing.JCheckBox();
        btnClear = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setText("Nombre del medicamento*");

        lblErrorName.setForeground(java.awt.Color.red);

        lblType.setText("Tipo de medicamento*");

        cmbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "analgésico", "analéptico", "anestésico", "antiácido", "antidepresivo", "antibiótico" }));
        cmbxType.setSelectedIndex(-1);

        lblErrorType.setForeground(java.awt.Color.red);

        lblSize.setText("Cantidad de producto*");

        lblErrorSize.setForeground(new java.awt.Color(255, 0, 0));

        lblDistributor.setText("Distribuidor Farmacéutico*");

        rdbtnFirst.setText("Cofarma");

        rdbtnSecond.setText("Empsephar");

        rdbtnThird.setText("Cemefar");

        lblErrorDistributor.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorDistributor.setToolTipText("");

        lblDeliverAddress.setText("Lugar de entrega*");

        lblErrorDeliverAddress.setForeground(new java.awt.Color(255, 0, 0));

        chckbxPrincipal.setText("Principal");

        chckbxSecondary.setText("Secundaria");

        btnClear.setText("Borrar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirmar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeliverAddress)
                    .addComponent(lblSize)
                    .addComponent(lblName)
                    .addComponent(lblType)
                    .addComponent(lblDistributor))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblErrorName)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdbtnFirst)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdbtnSecond)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdbtnThird))
                                    .addComponent(txtSize)
                                    .addComponent(cmbxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtName))
                                .addGap(82, 82, 82))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorSize)
                                    .addComponent(lblErrorType))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(chckbxPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chckbxSecondary)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblErrorDeliverAddress)
                        .addGap(152, 152, 152))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblErrorDistributor)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(cmbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbtnFirst)
                        .addComponent(rdbtnSecond)
                        .addComponent(rdbtnThird))
                    .addComponent(lblDistributor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorDistributor)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliverAddress)
                    .addComponent(chckbxPrincipal)
                    .addComponent(chckbxSecondary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorDeliverAddress)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnConfirm))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        lblErrorDeliverAddress.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       // Borramos el formulario a los valores iniciales
        txtName.setText("");
        lblErrorName.setText("");
        cmbxType.setSelectedIndex(-1);
        lblErrorType.setText("");
        txtSize.setText("");
        lblErrorSize.setText("");
        rdbtnGroup.clearSelection();
        lblErrorDistributor.setText("");
        chckbxPrincipal.setSelected(false);
        chckbxSecondary.setSelected(false);
        lblErrorDeliverAddress.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // Obtener valores del formulario
        String productName = txtName.getText();
        String productSize = txtSize.getText();
        String productType = cmbxType.getSelectedIndex() >= 0 ? cmbxType.getSelectedItem().toString() : "";
        String firstAddress = chckbxPrincipal.isSelected() ? "Calle de la Rosa n. 28 " : "";
        String secondAddress = chckbxSecondary.isSelected() ? "Calle Alcazabilla n. 3" : "";
        String distributor = "";
        if(rdbtnFirst.isSelected()) {
            distributor = rdbtnFirst.getText();
        }else if(rdbtnSecond.isSelected()) {
            distributor = rdbtnSecond.getText();
        }else if(rdbtnThird.isSelected()) {
            distributor = rdbtnThird.getText();
        }

        // Validar que el formulario este lleno con todos los campos.
        String commonInputError = "Por favor ingresar un valor.";
        String commonSelectionError = "Por favor seleccione un valor.";
        String errorName = productName.isEmpty() ? commonInputError : "";
        lblErrorName.setText(errorName);
        String errorSize = productSize.isEmpty() ? commonInputError : "";
        lblErrorSize.setText(errorSize);
        String errorType = productType.isEmpty() ? commonSelectionError : "";
        lblErrorType.setText(errorType);
        String errorDistributor = distributor.isEmpty() ? commonSelectionError : "";
        lblErrorDistributor.setText(errorDistributor);
        String errorDeliverAddress = (chckbxPrincipal.isSelected() || chckbxSecondary.isSelected()) ? "" : commonSelectionError;
        lblErrorDeliverAddress.setText(errorDeliverAddress);

        // Validar que el dato ingresado en la casilla de cantidad sea el un entero positivo
        int totalProduct = 0;
        try {
            totalProduct = Integer.parseInt(productSize);
            errorSize = totalProduct <= 0 ? "Ingresar un número mayor o igual a 1" : "";
            lblErrorSize.setText(errorSize);
        } catch(NumberFormatException e1) {
            lblErrorSize.setText("Número Invalido, solo se permiten enteros positivos.");
        }


        if(errorName.isEmpty() && errorSize.isEmpty() && errorType.isEmpty()
           && errorDistributor.isEmpty() && errorDeliverAddress.isEmpty()) {
            // Formateo de la data de pedido
            String frameTitle = "Pedido al distribuidor " + distributor;
            String unitFormat = totalProduct == 1 ? "unidad" : "unidades";
            String orderSummary = totalProduct + " " + unitFormat +" del " + productType + " " + productName;
            String fullAddress = "Para la farmacia situada en " + firstAddress;
            fullAddress = chckbxSecondary.isSelected() ? fullAddress + " y la situada en " + secondAddress : fullAddress;

            // Abrimos la ventana del detalle del pedido
            DetallePedido frame = new DetallePedido(orderSummary, fullAddress);
            frame.setTitle(frameTitle);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JCheckBox chckbxPrincipal;
    private javax.swing.JCheckBox chckbxSecondary;
    private javax.swing.JComboBox<String> cmbxType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDeliverAddress;
    private javax.swing.JLabel lblDistributor;
    private javax.swing.JLabel lblErrorDeliverAddress;
    private javax.swing.JLabel lblErrorDistributor;
    private javax.swing.JLabel lblErrorName;
    private javax.swing.JLabel lblErrorSize;
    private javax.swing.JLabel lblErrorType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblType;
    private javax.swing.JRadioButton rdbtnFirst;
    private javax.swing.JRadioButton rdbtnSecond;
    private javax.swing.JRadioButton rdbtnThird;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
